### ISSUE TITLE
Cannot compile sample app

### ISSUE THREAD

**Issue by Ricardo1980** [Instagram/IGListKit#635] opened 2017-04-10 22:19 UTC
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: Last version, master.
- iOS version(s): iOS 10
- CocoaPods/Carthage version: Last one.
- Xcode version: 8.2.1
- Devices/Simulators affected: iPhone 7 plus
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: 

Hello,
If I try to compile the sample code, I receive 2 errors.
Do you have the same problem?

<img width="1388" alt="screen shot 2017-04-10 at 23 15 03" src="https://cloud.githubusercontent.com/assets/738681/24885015/208b20fc-1e44-11e7-83f5-f30381f345df.png">

**Comment by heshamsalman** [comment] 2017-04-11 21:02
Doesn't seem to be an issue in the latest master. The first issue was fixed in #636, and merged in #637. 

Can't reproduce the error on the second issue.

**Comment by HumidBrains** [comment] 2017-04-11 21:55
Got exactly the same bug as @Ricardo1980

**Comment by jessesquires** [comment] 2017-04-11 22:32
yep, looks like this should be ok now

**Closed by jessesquires** 2017-04-11 22:32 UTC
Labels: bug, starter-task
