### ISSUE TITLE
Crash trying perform update data at end a request many times

### ISSUE THREAD

**Issue by kleiberjp** [Instagram/IGListKit#519] opened 2017-02-28 22:24 UTC
# New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2
- CocoaPods/Carthage version: Cocoapods 1.2.0
- Xcode version: 8.2.1
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): No
- Related issues:

I have a section with an horizontal section and theri adapter inside the main, the horizontal section has N number of objects and execute a request call for another objects of the horizontall section, when the process end and try performupdate the horizontall section , have the following crash when try making scroll so fast and update  the data at same time

On that moment when make scroll so fast and is executing request and calling the reload data the method crash and says:

```sh
"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert section 1 but there are only 1 sections after the update"
```

i have tried put the request in another thread with priority .userInitiated , thinking was isse of request, but notthing

here is a project test with the failure... if you scroll slowly, the working is normal, try making scroll so fast
[Test IGListKit Failure.zip](https://github.com/Instagram/IGListKit/files/839413/Test.IGListKit.Failure.zip)

**Comment by jessesquires** [comment] 2017-02-28 22:32
Thanks @kleiberjp !

Can you provide any more information here?

**Comment by kleiberjp** [comment] 2017-02-28 23:01
@jessesquires i have update the description of issue

**Comment by heumn** [comment] 2017-03-01 09:30
It would be much easier to help / understand the problem if you could provide an example project 😅 

Have you triple checked that the object diff identifiers are unique?

**Comment by rnystrom** [comment] 2017-03-01 13:47
+1 an example project would be _really_ helpful understanding the problem here

**Comment by kleiberjp** [comment] 2017-03-13 19:32
@rnystrom @heumn  @jessesquires  hi guys sorry by the late.. i have updated the issue description with the project test.. hope you can helpe with a solution pls

**Comment by rnystrom** [comment] 2017-03-15 13:00
@kleiberjp I'm having a little trouble getting this (really cool demo) to crash 😞 

One thing though, you're using a lot of embedded adapters. We discovered a crash w/ using a bunch of them like this fixed in #517. You might want to update your Podfile to point to the `master` branch of IGListKit and see if that solves things for you.

**Comment by kleiberjp** [comment] 2017-03-15 17:04
@rnystrom oh, did you try to scroll very very fast? to getting this, to me happens when I scroll fast fast, quickly I stopped, did not let reload downloaded items, and scroll quickly back up

**Comment by heumn** [comment] 2017-03-15 17:17
I downloaded the project and after I pointed it to master I am unable to make this crash. It seems like you were running into #517 :)


This should fix it as @rnystrom pointed out
`pod 'IGListKit', :git=> 'git@github.com:Instagram/IGListKit.git', :branch => 'master'

**Comment by kleiberjp** [comment] 2017-03-15 23:13
Sorry guys but i´m experimenting the same issue 👎  :( .. with the same project this is the stack trace of the crash

´´´
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert section 1 but there are only 1 sections after the update'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010586ad4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001052cc21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010586ee42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000104e6166d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   UIKit                               0x00000001065e4d71 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 7861
	5   UIKit                               0x00000001065efe72 -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 71
	6   UIKit                               0x00000001065f01b4 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 432
	7   UIKit                               0x00000001065effe1 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 91
	8   UIKit                               0x00000001065eff63 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74
	9   UIKit                               0x00000001065efeb8 -[UICollectionView performBatchUpdates:completion:] + 53
	10  IGListKit                           0x00000001047628fc -[IGListAdapterUpdater performBatchUpdatesWithCollectionView:] + 2972
	11  IGListKit                           0x00000001047654e7 __54-[IGListAdapterUpdater queueUpdateWithCollectionView:]_block_invoke + 359
	12  libdispatch.dylib                   0x0000000109bed978 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x0000000109c170cd _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x0000000109bf78a4 _dispatch_main_queue_callback_4CF + 406
	15  CoreFoundation                      0x000000010582ee49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00000001057f437d __CFRunLoopRun + 2205
	17  CoreFoundation                      0x00000001057f3884 CFRunLoopRunSpecific + 420
	18  GraphicsServices                    0x000000010b6eaa6f GSEventRunModal + 161
	19  UIKit                               0x0000000105c8ec68 UIApplicationMain + 159
	20  Test IGListKit Failure              0x000000010463415f main + 111
	21  libdyld.dylib                       0x0000000109c6368d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by rnystrom** [comment] 2017-03-15 23:55
@kleiberjp can you provide some detailed steps to reproduce?

I couldn't get a crash w/ the stack trace that you pasted. I did get a crash where a `UINib` couldn't be found. It looks like you're passing `nil` to the bundle. That might need to be a specific bundle.

**Comment by kleiberjp** [comment] 2017-03-16 00:01
ok the steps are easy:
In the moment the app load give scroll fast super hiper mega fast, in forwards and backwards, there will be a moment in wich is processing many data for the scroll and demanding append data, the library crash.

And could you please indicateme in wich class - line code have to set a nib ???

**Comment by heumn** [comment] 2017-03-16 08:38
I finally got it to crash again... Sorry for my misunderstanding :) To be able to help you debug I will see if I can figure out a way to get it to crash consistently. It is tiresome to sit here dragging down _insanely_ fast ;)

**Comment by rnystrom** [comment] 2017-03-16 13:54
@kleiberjp scrolling fast vertically or horizontally?

About the nib, its in `UtilsExtension.swift` where you extend `IGListCollectionContext` and dequeue a cell with `bundle: nil`.

**Comment by kleiberjp** [comment] 2017-03-16 15:21
@rnystrom vertically the scroll, well i check the failure trying to dequeue cell, normally how i´m instancing the cell with the class and not from the xib, consider not needed use a bundle.

@heumn i´m gonna check what you recommend

**Comment by jessesquires** [comment] 2017-04-11 22:39
Seems like this is resolved??

closing due to inactivity

**Closed by jessesquires** 2017-04-11 22:39 UTC
Labels: question

**Comment by KumariOS** [comment] 2017-05-20 16:09
Hi,
I am facing same problem when i have both horizontal and vertical scroll view. It 
I followed the example tutorial but it did not help me much.

I get error message saying:

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert section 0 but there are only 0 sections after the update'.`

This happens when i scroll very fast. For both vertical and horizontal cell i have images and i am downloading those images.

**Comment by KumariOS** [comment] 2017-05-20 16:10
@rnystrom @jessesquires , If this is fixed or you have solution, please help me.

**Comment by rnystrom** [comment] 2017-05-22 13:35
@KumariOS can you open a new issue for this? Also when you hit the exception do `po [IGListDebugger dump]` from lldb. And if you can get a sample reproducing the issue that would be very helpful.
