### ISSUE TITLE
Separate out the diffing capability into another framework?

### ISSUE THREAD

**Issue by ianterrell** [Instagram/IGListKit#534] opened 2017-03-09 20:30 UTC
The company I work for has been using various unidirectional data flow architectures in several production apps. One thing we have need for in that is a robust diffing tool for lists, which IGListKit provides. However, we have no need for the rest of the framework.

As the diffing capability can stand on its own, from our perspective it would be nice to be able to pull in that alone. It would additionally be easier to ramp developers up on our approach since they would not be distracted by the other features of IGListKit.

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by jessesquires** [comment] 2017-03-09 20:38
Duplicate of #53. See also: #365.

**Comment by jessesquires** [comment] 2017-03-09 20:39
Thanks @ianterrell ! 

We have a diffing subspec — does your team use CocoaPods?

**Closed** 2017-03-09 20:39 UTC
Labels: duplicate, question

**Comment by rnystrom** [comment] 2017-03-11 20:01
Check out the [installation guide](https://instagram.github.io/IGListKit/installation.html) for how to pull in just the diffing subspec. That'll only pull in stuff from [/Common](https://github.com/Instagram/IGListKit/tree/master/Source/Common).

**Comment by ianterrell** [comment] 2017-04-12 20:09
Thank you for the quick reply — I did not notice the subspec option originally. We are currently moving from CocoaPods to Carthage for most of our projects.
