### ISSUE TITLE
Crash on iOS 9.2.1

### ISSUE THREAD

**Issue by CurlyHeir** [Instagram/IGListKit#591] opened 2017-03-28 19:22 UTC
### General information
- `IGListKit` version: 2.1
- iOS version(s): 9.2.1
- Xcode version: 8.3
- Devices/Simulators affected: iPad 3  (MD368PL/A)

### log: 
http://crashes.to/s/664d621d31b

i have no access to device, and I can't reproduce this on other devices and iOS versions

**Comment by MarvinNazari** [comment] 2017-03-28 20:55
related to #554

**Comment by jessesquires** [comment] 2017-03-29 03:10
Going to close as a duplicate of #554

**Closed by jessesquires** 2017-03-29 03:10 UTC
Labels: bug, duplicate
