### ISSUE TITLE
Using IGListKit with Realm

### ISSUE THREAD

**Issue by Megaman63** [Instagram/IGListKit#624] opened 2017-04-05 05:30 UTC
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.0.0
- iOS version(s): 10
- Xcode version: 8
- Reproducible in the demo project? (Yes/No): No

I am trying to use IGListKit with Realm (config dataSource with realm object). I have annoying issue that performUpdates(animated: Bool, completion: IGListKit.IGListUpdaterCompletion? = nil) use object when it already removed from Realm. I need to check object.isInvalidated but i don't know how to forbid IGListKit use invalidated object. Any ideas?

**Comment by robertjpayne** [comment] 2017-04-06 04:11
@Megaman63 this is probably more a Realm issue than IGListKit, that flag is a realm specific flag about deleted objects if I'm not mistaken?

I'm not really sure there is any better way than manually checking it as you are.

**Comment by Megaman63** [comment] 2017-04-06 08:41
@robertjpayne manually checking do not work. If object has been deleted from Realm, IGListKit may hold link to this object and use it to implement diffable algorithm and app will be crashed. I think, best way to solve this problems - copy realm object and use it, but i am not sure :)

**Comment by MarvinNazari** [comment] 2017-04-06 17:55
@Megaman63 you can just try something like this

```swift

class VC: UIViewController {
    fileprivate var token: NotificationToken?

    fileprivate var users: Results<UserModel> {
        let realm = try! Realm()
        return realm.objects(UserModel)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        ...
        token = users.addNotificationBlock { [weak self] changes in
            if case .update = changes {
                self?.adapter.performUpdates(animated: false)
            }
        }
    }

    func objects(for listAdapter: IGListAdapter) -> [IGListDiffable] {
        return users.map { $0.diffable }
    }

```

**Comment by jessesquires** [comment] 2017-04-11 22:32
going to close this, but feel free to continue the discussion 😄

**Closed by jessesquires** 2017-04-11 22:32 UTC
Labels: question

**Comment by rnystrom** [comment] 2017-04-16 15:44
Calling on @TimOliver 😄

**Comment by jessesquires** [comment] 2017-04-16 19:09
Tom Oliver to the rescue 😉

**Comment by TimOliver** [comment] 2017-04-17 01:39
ROFL!! Gee whiz, thanks guys. 🤣

Umm, I believe @bigfish24 said he had a play with integrating Realm and IGListKit together and came up against a similar problem. The diffing algorithm doesn't seem to play nice with these ostensibly read-only Realm objects that won't be `nil`'d out, but can be invalidated if the underlying data is deleted.

I think @MarvinNazari' solution is the best for the time being. You can use a non-managed copy of the object to persist it in memory. It's not great since you lose all of Realm's live updates, but it should work.

At some point, time permitting, we'll have to see what we can do to make integrating Realm with IGListKit more seamless. :)

**Comment by Megaman63** [comment] 2017-04-17 11:19
The best way to solve the problem that i discovered is completely copy object and use it in 
`func objects(for listAdapter: IGListAdapter) -> [IGListDiffable] {
        var list : [IGListDiffable] = []
        if let posts = posts, !posts.isInvalidated {
            for post in posts {
                if !post.isInvalidated {
                    list.append(post.copiedPost)
                }
            }
        }
      return list

}

**Comment by MichaelLuoSyd** [comment] 2018-02-28 22:58
@rnystrom, am curious to know if we have any progress in igListKit working with Realm notification. If we use copiedObjects, any changes in Realm won't be reflected in the UI. However, if we add Realm notification to the objects array, it always causes crash as follows:  
attempt to delete item 5 from section 0 which only contains 1 items before the update

Any help to solve this crash will be appreciated.

**Comment by MichaelLuoSyd** [comment] 2018-03-01 01:09
@rnystrom, after tweaked the realm notificationblock, iglistkit works fine with realm now.

**Comment by rnystrom** [comment] 2018-03-01 18:13
@MichaelLuoSyd I bet that's from how Realm mutates its models. IGListKit is really safest w/ an immutable model architecture. We don't officially support integration w/ Realm (and I've honestly never used Realm), so I can't offer great advice on integrating the two.

**Comment by MichaelLuoSyd** [comment] 2018-03-05 00:59
@rnystrom, Thanks for your reply. My workaround for igListKit with realm notification is to add notification to realm objects and call adapter.performUpdates in the changeBlock. In isEqual(), only compare object's primary key and those properties which feed the UI to drive the UI update. In didSelectItem(at index:), query Realm according to the object's primary key so the object will always be the updated one. Working as charm.

**Comment by TimOliver** [comment] 2018-03-05 10:45
I still haven't had an in-depth play with IGListKit (sorry guys!), but maybe I can talk a little bit about how Realm collections work in the hopes a better solution can be found.

Realm collection items are live-updating. Meaning if there is a Realm collection object representing the results of a query, and something else in the app causes the results of that query, that previous Realm collection object will be updated with the new results upon the next main run-loop iteration. Without registering for notifications, those mutations are silent, and can easily cause inconsistency exceptions with `UITableView` if not properly handled.

Realm's granular change notification system was designed specifically in mind so that it could be used to drive the insert/refresh/delete batch operations available in `UITableView` / `UICollectionView`. Ie, when the notification block from Realm is triggered, the state of the representing Realm collection object, and the index paths of what changed are compatible with `UITableView`.

As long as there's logic to let IGListKit know when a Realm collection has mutated, the two *should* work together fine. But if IGListKit has a mechanism of internally making copies of collections, that would definitely be an anti-pattern in terms of handling Realm.

In any case, I'm really busy at the moment (Just moved countries!), so I can't commit any time to trying it out now, but I've got an incoming side-project where I'm considering using IGListKit and Realm together, so at that point, I'll give it a proper try and see how that goes. :)

**Comment by sheff1422** [comment] 2018-05-25 14:20
@TimOliver Do you have any updates regarding this topic? We are using Realm and IGListKit in our project and that is really interesting to hear more about best practice here.

**Comment by Megaman63** [comment] 2018-05-30 18:33
@sheff1422 
Yeah, i have some suggestions.
Of course you will loose all benefits of lazy realm objects when you convert 5000 objects to plain at one time. In general, pass 5000 objects to datasource is not good idea... 
I think there should be some kind of pagination (or infinite scroll) service, so when collection view scrolls to bottom you request next 20 objects and convert it to plain structs. So you should implement service which would store lazy `Result<YouRealmObject>` evaluated by some your search predicate and return plain object by your request only when it is necessarily. You should prefer use SortDescriptor instead of your manual sort to retrieve sorted `Result<YouRealmObject>`

**Comment by sheff1422** [comment] 2018-05-31 13:36
@Megaman63 
Currently i have smth similar.
The flow looks like this
1) Fetch section groups with Result<YouRealmObject> in each group
2) When the IGList starts to load sections, it makes that section by section so results are loaded during the scroll. However the main problem here is that lazy loading is performed on the main thread. But due to the complexity of predicate it gives performance issues. 
So based on you recommendation it will be better to make that conversion in a background thread while loading sections. 
If all goes fine i will post more detailed info here, it may probably help someone.

**Comment by TimOliver** [comment] 2022-04-09 08:30
G'day folks! I hope everyone in here's managed to stay safe and well. It's been a while. 😆

A fair bit's changed on my end. I don't work for Realm anymore (full disclosure: I work for Instagram now! 🎉), but I'm still a big fan of Realm in everything that they're doing and I try to periodically keep tabs on what they're doing. 😊

I meant to come and address this a little earlier. It looks like Realm actually did release a new feature that should effectively solve the issues we were discussing in here (hopefully!). 🥳

[In mid-2020](https://www.mongodb.com/developer/article/realm-database-and-frozen-objects/), Realm released a new feature of Realm Core called frozen objects. The concept is that you can choose to "freeze" a set of results from a Realm, and this immutable result set can then be freely passed between threads. In that vein, these frozen objects should work with IGListKit's diffing engine to enable proper integration with IGListKit without having to do the manual deep copies that were being discussed before.

The Realm Swift documentation for how to handle frozen Realm objects is [available in the threading section of the documentation](https://www.mongodb.com/docs/realm/sdk/swift/advanced-guides/threading/#frozen-objects).

If anyone is still interested in integrating Realm and IGListKit in here, please give this a try and let us know how you go! 🙏

**Comment by Megaman63** [comment] 2022-04-09 13:42
Congratulations to you and have fun with your new job :) 
On my new job we have Realm, and the team that I joined to uses the same pattern - "converted to plain structs realm objects and no lazy benefits")) Looks like this pattern is very common.
And we don't use IGListKit. So for me this thread is not so interesting now 🙃

**Comment by TimOliver** [comment] 2022-04-10 14:01
Haha thanks a lot! I still can't believe it myself! 😁

Ahh okay! Good to hear you're still using Realm in your new job! Ahh, okay. If that pattern works for your company's needs, that's good to hear. I definitely also heard the same that a lot of folks went with performing manual copies of objects of Realm objects over the years. 

Reaffirming what I said above (assuming it hasn't changed since then 😅), when you make copies of Realm objects, you do miss out on all of the advantages of the "live object" paradigm and memory efficiencies (Since you're forcing Realm to page all the data into memory up front). But if your app doesn't actually need to rely on those features, and you've confirmed it's not impacting memory at all, it's completely fine.

Awww! Well, if your company's project ever does come up with a feature that uses `UICollectionView`, I hope you consider IGListKit at that point. 😉 All the best!
