### ISSUE TITLE
Update a cell works as Insert/Delete

### ISSUE THREAD

**Issue by lucabartoletti** [Instagram/IGListKit#297] opened 2016-12-07 11:41 UTC
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 1.0.0

I'm writing my own CollectionView Layout 

I'd like to perform custom animations when a cell is Updated/Inserted/Deleted/Moved

As a first step I was aiming to just remove the fade in/fade out effect provided by the UICollectionViewFlowLayout.
I implemented a subclass of UICollectionViewFlowLayout to tweak this behaviour. After some digging I found that[ in IGListKit the cell updates are converted to a remove/insert](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L275). 
This means that when I receive the calls to my UICollectionViewFlowLayout I see only Insert and remove.

Have you experienced this using the library? Do you have any workaround for this problem where in the layout implementation we can't distinguish between an update or an insert/delete?

**Comment by rnystrom** [comment] 2016-12-07 14:12
@lucabartoletti good question! Have you started using the IGListKit and your custom layout yet to see what mutations the layout receives?

FWIW `reloadSections:` and `reloadItemsAtIndexPaths:` are _unsafe_ to use in `performBatchUpdates:`. In fact, `UICollectionView` converts the transactions to delete+insert under the hood.

Correct me if I'm wrong, but you're asking about what to do with `UICollectionUpdateActionReload` in `-[UICollectionViewLayout prepareForCollectionViewUpdates:]`, right?

In Instagram we have custom animations for basically everything. Animated reloads are just cross fades (similar to flow layout) and delete+insert results in the same effect.

**Comment by lucabartoletti** [comment] 2016-12-07 14:26
Yes, i'm trying to do a specific animation if it's a NSCollectionUpdateActionReload

The problem is that at the moment I can't distinguish a Reload from an Insert cause even when the action is an update than is converted to an an insert/delete

While i was trying to track down the source of the problem I found this [line of code.](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L275) where it looks like that IGListKit is doing that conversion from Reload to Insert/Remove. So it doesn't like that is an internal UICollectionView thing. 

From my tests at the moment I can't use NSCollectionUpdateActionReload so I wonder if you have any hint about this use case

**Comment by rnystrom** [comment] 2016-12-07 14:55
re: not an internal `UICollectionView` thing, like I mentioned, any reload operation inside `performBatchUpdates:` is unsafe and actually not officially supported, those methods are meant to be called outside of the batch updates block. Since we use batch updates for all transactions (barring manual updates).

For these custom animations, is the insert/delete like a scaling animation and reload just a fade or something?

Might be worth us diving into the internals of how these actions are generated and see if we can MITM them so the action is still a reload, even though we tell collection view to still delete+insert.

**Comment by lucabartoletti** [comment] 2016-12-07 16:07
At the moment would be enough to recognise that is a reload and not an insert/remove so that i can

- disable the fade in/ fade out if it's a reload
- otherwise keep the default UICollectionViewFlowLayout

**Comment by rnystrom** [comment] 2017-01-04 19:28
@Adlai-Holler it does correctly convert them into delete+insert, but if the item is naturally shifted from delete+insert+move it'll fail when using section operations.

[UICollectionViewReloadDisplacement.zip](https://github.com/Instagram/IGListKit/files/685646/UICollectionViewReloadDisplacement.zip)

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to perform an insert and a move to the same section (4)'
```

This setup will crash 100% of the time, but not every insert+delete+move will cause UICollectionView to throw.

**Comment by danielgalasko** [comment] 2017-02-03 12:46
This is a tricky one because when this is used in something like UITableView with an automatic transition mode, these updates look significantly different to a delete/insert on the same cell. What would you recommend doing then in this scenario?

**Comment by danielgalasko** [comment] 2017-02-03 12:50
The diff result without calling `forBatchUpdates` will return `moves` that need to be translated into deletions and insertions but then at least we get updates properly. So I think for now all I can do is just get the raw diff and then work transform moves into insert/deletes

**Comment by rnystrom** [comment] 2017-02-05 03:01
@danielgalasko we used to have a method that would do just that, might be something we could look into restoring.

**Comment by danielgalasko** [comment] 2017-02-06 07:36
For now I just looked at the implementation for `resultForBatchUpdates` and made my own extension that mimics it without using the replace updates for inserts and deletes i.e.

```
    // convert all update+move to delete+insert
    const NSUInteger moveCount = moves.count;
    for (NSInteger i = moveCount - 1; i >= 0; i--) {
        IGListMoveIndex *move = moves[i];
        if ([filteredUpdates containsIndex:move.from]) {
            [filteredMoves removeObjectAtIndex:i];
            [filteredUpdates removeIndex:move.from];
            [deletes addIndex:move.from];
            [inserts addIndex:move.to];
        }
    }
```

**Comment by rnystrom** [comment] 2017-03-22 15:45
Closing for now since this is working as intended for IGListKit to avoid errors in `UICollectionView`.

**Closed by rnystrom** 2017-03-22 15:45 UTC
Labels: question
