### ISSUE TITLE
Add option to maintain scroll position when performing updates.

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#242] opened 2016-11-21 22:08 UTC
Internally, we discussed adding this to the API, as it's likely a common use case.

We've built this for IG Direct, where we keep the scroll position while loading previous messages.

Proposed addition:

```objc
// IGListAdapter

- (void)performUpdatesAnimated:(BOOL)animated 
           fixedScrollPosition:(BOOL)fixedScrollPosition
                    completion:(nullable IGListUpdaterCompletion)completion;
```

I'm leaning toward **adding** this method, **not** replacing:

```objc
- (void)performUpdatesAnimated:(BOOL)animated completion:(nullable IGListUpdaterCompletion)completion;
```

The existing `performUpdatesAnimated:` would call the new one, passing `NO` for `fixedScrollPosition:`

Thoughts?

**Comment by jessesquires** [comment] 2016-11-21 22:09
Alternative method spelling:

- `maintainScrollPosition:` 
- `keepScrollingPosition:`

?

**Comment by rnystrom** [comment] 2016-11-21 22:52
@jessesquires Ya I agree w/ adding a new method. It'll make upgrading a lot smoother for a method that is going to be used _a lot_.

I think I like "maintainScrollPosition".

Also I don't think we can do `animated:YES maintainScrollPosition:YES` and do an animated update w/ fixed scroll position. Maybe we have `performUpdatesMaintainingScrollPositionWithCompletion:`? Or something like that.

Side note, I have a feeling this is how [`animateWithDuration:animations:`](https://developer.apple.com/reference/uikit/uiview/1622418-animate) became [`animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:`](https://developer.apple.com/reference/uikit/uiview/1622594-animatewithduration) 😂

**Comment by jessesquires** [comment] 2016-11-21 23:18
@rnystrom lol 😆  yup.

+1 for maintainScrollPosition

> Also I don't think we can do `animated:YES maintainScrollPosition:YES` and do an animated update w/ fixed scroll position. 

Derp. You're right. In Direct, we pass `animated:NO`. 

Now it definitely makes sense *add* this as a new method. 💯

**Comment by rnystrom** [comment] 2016-12-02 15:18
@jessesquires Check out internal comments on diff, I'm fine punting on this feature for now, we can pick it into a minor release. Lmk what you think.

**Comment by jessesquires** [comment] 2016-12-02 16:27
Yep was thinking the same 👍

**Comment by michalkalinowski-** [comment] 2016-12-12 13:21
Any tips on implementing this? I need to maintain scroll position in my app when items are added on top of the list.
I've seen old issue on @jessesquires repo: https://github.com/jessesquires/JSQMessagesViewController/issues/441 
and I'm trying to implement something similar in `listAdapterUpdaterWillPerformBatchUpdatesWith collectionView + listAdapterUpdaterDidPerformBatchUpdatesWith collectionView` delegate methods, but I'm still getting visual glitches. 

The only different solution I see is to modify layout itself to insert cells at negative y values but that seems like a lot of work.

If it's something that can be implemented in IGListkit I'm more than happy to take this task, just need some tips on how to code that.

**Comment by rnystrom** [comment] 2016-12-12 14:47
@michalkalinowski- we have this internally at Instagram and are going to work on porting it to be more generic.

The basics of it are:

- Save the topmost visible item in the collection view
- Save the content offset
- Do an unanimated update
- Find the position of the previous item above
- Calculate the delta with the previous content offset and new content offset
- Adjust the content offset

**Comment by zhubofei** [comment] 2017-01-12 13:25
@rnystrom What if the saved topmost item is removed (or moved) after the update? Do we just use the previous content offset as a fallback?

**Comment by jessesquires** [comment] 2017-02-28 01:14
This is an additive change. Bumping to 3.1.0 release.

**Comment by zhubofei** [comment] 2017-03-29 23:48
@jessesquires @rnystrom You guys want to do this one internally or can I take it? Have some free time recently👷.

**Comment by rnystrom** [comment] 2017-03-30 01:39
@zhubofei We've got this built internally and just need to move it out. We'll release it once we get a chance 😅

**Comment by darrarski** [comment] 2017-04-21 21:54
@rnystrom any news about this feature? If open sourcing the solution is not on your priority list right now, could you just provide some hints so I can try to implement it on my own?

**Comment by rnystrom** [comment] 2017-04-21 22:44
@darrarski its on our radar for after 3.0 release. Here's a super short writeup on how to get it working tho:

https://github.com/Instagram/IGListKit/issues/644#issuecomment-294359113

**Comment by darrarski** [comment] 2017-04-25 01:12
@rnystrom just FYI, I manage to solve it without saving visible cell. Perhaps it's not ideal solution, but works for my needs. I ended with creating extension to `UIScrollView` that calculates and allows to set "reversed" content offset: [UIScrollView_ReversedContentOffset.swift](https://github.com/darrarski/Messages-iOS/blob/3ae70385a42753f8889f85c3eac07ee4a42a1b43/MessagesApp/UI/Helpers/UIScrollView_ReversedContentOffset.swift)

By default, content offset is measured from the top of the view, and is preserved when updating content. The tick it to preserve content offset measured from the bottom of the view instead.

I am using it like this:
```swift
let reversedContentOffset = listCollectionView.reversedContentOffset
listAdapter.performUpdates(animated: false) { [weak self] _ in
    self?.listCollectionView.reversedContentOffset = reversedContentOffset
}
```

**Comment by Codeido** [comment] 2017-07-19 16:38
@darrarski I think that this solution doesn't work properly with cells that have dynamic height

**Comment by darrarski** [comment] 2017-07-19 17:13
@Codeido it works pretty well here: https://github.com/darrarski/Messages-iOS 
As you can see the cells can have various height, depending on contained text. I understand that this isn't a perfect solution for everyone's needs. Perhaps it just doesn't work for your case, but I can't tell without more info about how you are using it.

**Comment by tunidev** [comment] 2017-10-17 19:52
What the status of this ?

**Comment by sheinix** [comment] 2017-11-08 16:05
The library has been deprecated, but still, anyone with a solution for this?

**Comment by darrarski** [comment] 2017-11-08 16:17
@sheinix yes, please check out my comments above and this repo: [Messages-iOS](https://github.com/darrarski/Messages-iOS). You should be able to get the same behaviour without `IGListKit`, just check out my implementation.

**Comment by sheinix** [comment] 2017-11-08 17:04
@darrarski you have` listAdapter.performUpdates(animated: false)` that it isn't on JSQMessagesViewController. Are you suggesting to use `self.collectionView.performBatchUpdates` ?

**Comment by darrarski** [comment] 2017-11-08 18:14
@sheinix it doesn't matter how you update your collection, you can do it using plain `UIKit` API or use `IGListKit` or other library to do it for you. The topic is about preserving scroll position when updating the collection which my implementation somehow solves (perhaps not it all possible cases).

**Comment by yood** [comment] 2018-05-29 16:52
https://github.com/Instagram/IGListKit/issues/242#issuecomment-266448871 doesn't work for me. The results for `performUpdates(animated: false)` are rendered for a few frames before the completion block (with the `setContentOffset`) is called.

It looks like the issue is the `CATransaction` that wraps non-animated batch updates, which is committed before the completion blocks are called. When I committed the `CATransaction` after the completion blocks instead, my `setContentOffset` in the completion block was correctly applied before the UICollectionView rendered the updates, resulting in a smooth prepending experience.

https://github.com/Instagram/IGListKit/blob/290d592983713c3ef82eb4950ba773a0059563a2/Source/IGListAdapterUpdater.m#L237-L244

**Comment by HowardCsie** [comment] 2018-08-13 15:59
@yood Thanks.
from
```
[CATransaction begin];
[CATransaction setDisableActions:YES];
[collectionView performBatchUpdates:^{
    batchUpdatesBlock(result);
} completion:^(BOOL finished) {
    [CATransaction commit];
    batchUpdatesCompletionBlock(finished);
}];
```
to
```
[CATransaction begin];
[CATransaction setDisableActions:YES];
[collectionView performBatchUpdates:^{
    batchUpdatesBlock(result);
} completion:^(BOOL finished) {
    batchUpdatesCompletionBlock(finished);
    [CATransaction commit];
}];
```
make it more smooth.

**Comment by hahtml** [comment] 2019-02-28 20:31
Any progress on this one? Looks like this is a commonly used feature. 😆

**Comment by spnkr** [comment] 2019-05-01 18:05
bump

**Comment by hydyy** [comment] 2019-06-13 08:41
Any progress on this one? Looks like this is a commonly used feature.

**Comment by hydyy** [comment] 2019-06-13 13:54
@rnystrom

**Comment by hahtml** [comment] 2019-06-13 22:41
The only promising way I find to solve the stutter/visual glitch issue is to use a custom `UICollectionViewFlowLayout`, override `prepare` func and set offset there.

This is the only solution to maintain scroll position smoothly in our case.

**Comment by qhhonx** [comment] 2019-06-14 02:46
> The only promising way I find to solve the stutter/visual glitch issue is to use a custom `UICollectionViewFlowLayout`, override `prepare` func and set offset there.
> 
> This is the only solution to maintain scroll position smoothly in our case.

How about overriding this API which gives custom target contentOffset when performBatchUpdates.
```Objective-C
- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedContentOffset NS_AVAILABLE_IOS(7_0); // a layout can return the content offset to be applied during transition or update animations
```

However, I doubt that it is not feasible to maintain every performUpdates situation except for loading newer/older data.

In our production use case, the above API overrides can achieve fixedScrollPosition while performUpdates to loading older messages like iMessage App.

**Comment by sasojadrovski** [comment] 2019-09-18 21:42
> The only promising way I find to solve the stutter/visual glitch issue is to use a custom `UICollectionViewFlowLayout`, override `prepare` func and set offset there.
> 
> This is the only solution to maintain scroll position smoothly in our case.

Could you please provide an example on how to achieve this? It would be greatly appreciated! Thanks! 😊

**Comment by danqing** [comment] 2019-12-05 05:09
@hahtml 's approach is the only one that works for me.

I'm not sure if iOS or IGListKit have any change in the last 2 years that breaks other solutions, but I've tried almost everything in this thread and all others give me glitch. @yood 's approach may work, but I'm hesitant to change that order because I'm using the callback in other places too and I don't want to cause any additional trouble.

```swift
import UIKit

class ChatMessageLayout: UICollectionViewFlowLayout {

  var maintainOffset = false {
    didSet {
      self.currentHeight = self.collectionView?.contentSize.height
    }
  }
  private var currentHeight: CGFloat!

  override func prepare() {
    if self.maintainOffset, let cv = self.collectionView {
      cv.contentOffset = CGPoint(x: cv.contentOffset.x, y: cv.contentOffset.y + collectionViewContentSize.height - self.currentHeight)
      self.maintainOffset = false
    }
  }

}
```

Usage:

```swift
self.layout.maintainOffset = true
self.adapter.performUpdates(animated: false)
```

**Comment by lorixx** [comment] 2019-12-05 06:24
Yeah, maintaining the scroll position should not be IGListKit's job, in IG we also use the UICollectionViewLayout's API to maintain the currentOffset or maintaining the same distance from the VERY bottom.

There are two way to maintain scroll position:
- Maintain the same distance from the top, which means keeps the same contentOffset;
- Maintain the same distance from the bottom, we need to do some math to get the right contentOffset.

I would suggest you do it:
1. Save the scroll position state right before calling -performUpdatesAnimate:completion:
2. Restore the scroll position in the `finalizeCollectionViewUpdates` of your customized UICollectionViewFlowLayout

**Closed** 2019-12-05 06:25 UTC
Labels: enhancement

**Comment by lsdimagine** [comment] 2020-05-09 20:25
> @hahtml 's approach is the only one that works for me.
> 
> I'm not sure if iOS or IGListKit has any change in the last 2 years that breaks other solutions, but I've tried almost everything in this thread and all others gave me glitch. @yood 's approach may work, but I'm hesitant to change that order because I'm using the callback in other places too and I don't want to cause any additional trouble.
> 
> ```swift
> import UIKit
> 
> class ChatMessageLayout: UICollectionViewFlowLayout {
> 
>   var maintainOffset = false {
>     didSet {
>       self.currentHeight = self.collectionView?.contentSize.height
>     }
>   }
>   private var currentHeight: CGFloat!
> 
>   override func prepare() {
>     if self.maintainOffset, let cv = self.collectionView {
>       cv.contentOffset = CGPoint(x: cv.contentOffset.x, y: cv.contentOffset.y + collectionViewContentSize.height - self.currentHeight)
>       self.maintainOffset = false
>     }
>   }
> 
> }
> ```
> 
> Usage:
> 
> ```swift
> self.layout.maintainOffset = true
> self.adapter.performUpdates(animated: false)
> ```

hmm it doesn't work for dynamic cells. The collectionViewContentSize.height is not accurate in `prepare`

**Comment by mohanbright** [comment] 2020-05-31 15:12
> ```swift
> let reversedContentOffset = listCollectionView.reversedContentOffset
> listAdapter.performUpdates(animated: false) { [weak self] _ in
>     self?.listCollectionView.reversedContentOffset = reversedContentOffset
> }
> ```

Didn't worked for cells with dynamic height

**Comment by rcaos** [comment] 2021-05-10 21:42
This works for me. Thanks!

> @hahtml 's approach is the only one that works for me.
> 
> I'm not sure if iOS or IGListKit has any change in the last 2 years that breaks other solutions, but I've tried almost everything in this thread and all others gave me glitch. @yood 's approach may work, but I'm hesitant to change that order because I'm using the callback in other places too and I don't want to cause any additional trouble.
> 
> ```swift
> import UIKit
> 
> class ChatMessageLayout: UICollectionViewFlowLayout {
> 
>   var maintainOffset = false {
>     didSet {
>       self.currentHeight = self.collectionView?.contentSize.height
>     }
>   }
>   private var currentHeight: CGFloat!
> 
>   override func prepare() {
>     if self.maintainOffset, let cv = self.collectionView {
>       cv.contentOffset = CGPoint(x: cv.contentOffset.x, y: cv.contentOffset.y + collectionViewContentSize.height - self.currentHeight)
>       self.maintainOffset = false
>     }
>   }
> 
> }
> ```
> 
> Usage:
> 
> ```swift
> self.layout.maintainOffset = true
> self.adapter.performUpdates(animated: false)
> ```

**Comment by aimalygin** [comment] 2021-10-17 21:32
Maybe someone will be useful. I solve this issue in [StableCollectionViewLayout](https://github.com/aimalygin/StableCollectionViewLayout).
It is based on the UICollectionViewLayout approach using prepare(forCollectionViewUpdates:) and targetContentOffset(forProposedContentOffset:) methods.
